#!/bin/bash
cd ~/ted
status=0
cargo build || exit 1
RUST_BACKTRACE=1 cargo test -q -p ted_core || status=1
RUST_BACKTRACE=1 cargo test -q -p ted_common_commands || status=1
RUST_BACKTRACE=1 cargo test -q -p ted || status=1
exit $status
