#!/bin/bash

cd ~/ted || exit 1

cargo build || exit 1

if [ "$1" = "--doc" ]; then
    tests=""
else
    tests="--tests"
fi
tests+=" -- -q"

status=0
RUST_BACKTRACE=1 cargo test -p ted_core $tests || status=1
RUST_BACKTRACE=1 cargo test -p ted_common_commands $tests || status=1
RUST_BACKTRACE=1 cargo test -p ted_git $tests || status=1
RUST_BACKTRACE=1 cargo test -p ted_mark $tests || status=1
RUST_BACKTRACE=1 cargo test -p ted_kill_ring $tests || status=1
RUST_BACKTRACE=1 cargo test -p ted_user_cfg $tests || status=1
RUST_BACKTRACE=1 cargo test -p ted $tests || status=1
exit $status
