#!/bin/bash

cd "$(dirname "$0")" || exit 1

cargo build || exit 1

status=0
for package in $(find . -maxdepth 1 -type d -name 'ted_*' | perl -pe 's|\./||' | sort) ted; do
    RUST_BACKTRACE=1 cargo test -p $package --tests -- -q || status=1
done

if [ "$1" = "--doc" ]; then
    if [ $status -ne 0 ]; then
        exit $status;
    fi

    for package in $(find . -maxdepth 1 -type d -name 'ted_*' | perl -pe 's|\./||' | sort) ted; do
        RUST_BACKTRACE=1 cargo test -p $package -- -q || status=1
    done
fi

exit $status
