[package]
name = "ted_renderers"
version = "0.1.0"
authors = ["Czipperz <czipperz@gmail.com>"]

[dependencies]
ted_core = { path = "../ted_core" }
pancurses-result = "0.5.1"
parking_lot = "*"
gdk = "0.9.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]
