[package]
name = "ted_other_window"
version = "0.1.0"
authors = ["Czipperz <czipperz@gmail.com>"]

[dependencies]
ted_core = { path = "../ted_core" }
ted_common_commands = { path = "../ted_common_commands" }
parking_lot = "*"
